### ISSUE TITLE
Think about new name for project

### ISSUE THREAD

**Issue by pawelpluta** [pawelpluta/extreme-programming-methodologies#1]
During the discussion with @apokralipsa, it came out that presented ideas do not fall under [Extreme programming](https://en.wikipedia.org/wiki/Extreme_programming), as it is clearly defined. We should think about a new name to use.
Suggested names are:
* Rad Programming Methodologies ("rad" as a new word for "awesomeness" promoted by teenage mutant ninja turtles), but it appears there is already some [RAD development](https://blog.capterra.com/what-is-rapid-application-development/)

Any other suggestions?

Btw. I find mutant ninja turtles pretty badass.

**Comment by bandrzejewski** [comment]
During my evening saturday 'lying on the sofa' session, I came up with the:

- Supreme Programming Methodologies  - explanation: as Extreme Programming rules are very useful and imho works great during development, the majority of the developers across the world, probably don't follow them. Although 'new' methodologies described here, are probably more common and broadly used (probably in a lot of cases developers are not aware they are following them!) - therefore they are Superior.

**Comment by pawelpluta** [comment]
Earlier today got small conversation with @bslota. He suggested `not that extreme programming methodologies`, what evolved to `not so extreme programming methodologies` and later to `not too extreme programming methodologies`. I was very keen on to `'not too'` name, as it had some gag in it.

Right now I find `Supreme` much better. For me it is a symbol for being overpriced, but that how it sounds can make people think it is a real thing. _you have my bow_

**Comment by pawelpluta** [comment]
Set up the name to Supreme Programming Methodologies.
